#!/bin/bash

HADOOP_PREFIX=/usr/local/hadoop

. $HADOOP_PREFIX/etc/hadoop/hadoop-env.sh

/usr/sbin/sshd

if [ ! -f /data/hadoop/.init ]
then
    /usr/local/hadoop/bin/hdfs namenode -format
    touch /data/hadoop/.init
fi

rm -f /tmp/*.pid

$HADOOP_PREFIX/sbin/start-dfs.sh
$HADOOP_PREFIX/sbin/start-yarn.sh

