#!/bin/bash

. /hadoop.env

DAEMONS=${DAEMONS:-namenode,datanode,secondarynamenode,resourcemanager,nodemanager}
DAEMONS=$(echo $DAEMONS | sed 's/,/ /g')

for daemon in ${DAEMONS}
do
    echo Daemon $daemon...
    case $daemon in
	namenode)
	    if [ ! -f /data/hadoop/.namenode_formatted ]
	    then
		/usr/local/hadoop/bin/hdfs namenode -format
		touch /data/hadoop/.namenode_formatted
	    fi
	    /usr/local/hadoop/sbin/hadoop-daemon.sh start namenode
	    ;;
	secondarynamenode|datanode)
	    /usr/local/hadoop/sbin/hadoop-daemon.sh start $daemon
	    ;;
	resourcemanager|nodemanager|proxyserver)
	    /usr/local/hadoop/sbin/yarn-daemon.sh start $daemon
	    ;;
	*)
	    echo Daemon $daemon is not something I know how to start.
    esac
done


