#!/bin/bash

HADOOP_PREFIX=/usr/local/hadoop

. $HADOOP_PREFIX/etc/hadoop/hadoop-env.sh

rewrite() {
    cat $1 | \
    sed "s#@NAMENODE_URI@#${NAMENODE_URI}#" |
    sed "s#@DFS_REPLICATION@#${DFS_REPLICATION}#" > $1.tmp
    mv $1.tmp $1
}

NAMENODE_URI=${NAMENODE_URI:-hdfs://localhost:9000}
DFS_REPLICATION=${DFS_REPLICATION:-1}

rewrite $HADOOP_PREFIX/etc/hadoop/core-site.xml
rewrite $HADOOP_PREFIX/etc/hadoop/hdfs-site.xml

DAEMONS=${DAEMONS:-namenode,datanode,secondarynamenode,resourcemanager,nodemanager}
DAEMONS=$(echo $DAEMONS | sed 's/,/ /g')

for daemon in ${DAEMONS}
do
    echo Daemon $daemon...
    case $daemon in
	namenode)
	    if [ ! -f /data/hadoop/.namenode_formatted ]
	    then
		/usr/local/hadoop/bin/hdfs namenode -format
		touch /data/hadoop/.namenode_formatted
	    fi
	    /usr/local/hadoop/sbin/hadoop-daemon.sh start namenode
	    ;;
	secondarynamenode|datanode)
	    /usr/local/hadoop/sbin/hadoop-daemon.sh start $daemon
	    ;;
	resourcemanager|nodemanager|proxyserver)
	    /usr/local/hadoop/sbin/yarn-daemon.sh start $daemon
	    ;;
	*)
	    echo Daemon $daemon is not something I know how to start.
    esac
done


